org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=3
systemProp.file.encoding=utf-8

###########################
#### Gradle properties ###
#########################
group=me.srrapero720

##########################
#### Mod information ####
########################
modid=watervision
modname=WaterVision
# The mod version. See https://semver.org/
modversion=0.1.0-alpha
modauthors=SrRapero720
modcredits=Powered by WaterMedia
moddesc=Record, Watch and Broadcast videos in game
license=PolyForm Strict License 1.0.0
github=SrRapero720/watervision

#####################
#### Enviroment ####
###################
javaversion=21
modloader=FORGE
modloadershort=FG
minecraftversion=1.21.1
minecraftrange=[1.21.1,1.21.2)
forgeversion=52.1.3
forgerange=[52.1.3,)
fmlrange=[52,)
mappingschannel=official
mappingsversion=1.21.1
modrinthid=dGGbEGoV
curseforgeid=1167473

#######################
#### Dependencies ####
#####################
watermediaversion=2.1.30
watermediarange=[2.1.30,2.2)

#######################
#### Mixins config ###
#####################
mixinextra_version=0.3.5
mixinextra_version_range=[0.3.5,)
mixin_file_suffix=mixin.json
mixin_refmap_suffix=mixin-refmap.json