org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=3
systemProp.file.encoding=utf-8

group=me.srrapero720
modid=watervision
modname=WaterVision TFOT
modversion=1.1.0
modauthors=TFOT, SrRapero720
modcredits=TFOT fork powered by WaterMedia
moddesc=TFOT cinematic video player powered by WaterMedia
license=PolyForm Strict License 1.0.0
github=77Romain77/watervision-compat-watermedia-v3
javaversion=17
modloader=FORGE
minecraftversion=1.20.1
minecraftrange=[1.20.1,1.20.2)
forgeversion=47.4.6
forgerange=[47.4,)
fmlrange=[47,)
mappingschannel=parchment
mappingsversion=2023.09.03-1.20.1
modrinthid=dGGbEGoV
curseforgeid=1167473
watermediaversion=3.0.0.23
watermediarange=[3.0.0.23,3.0.0.24)
voicechat_api_version=2.6.13
mixin_version=0.8.5
mixin_fabric_version=0.12.5
mixinextra_version=0.3.5
mixinextra_version_range=[0.3.5,)
mixin_file_suffix=mixin.json
mixin_refmap_suffix=mixin-refmap.json