modLoader="javafml" #mandatory
loaderVersion="${fmlrange}"
license="${license}"
issueTrackerURL="https://github.com/${github}/issues" #optional

[[mods]] #mandatory
   modId="${modid}" #mandatory
   version="${modversion}" #mandatory
   displayName="${modname}" #mandatory
   displayTest="MATCH_VERSION"
   logoFile="pack.png" #optional
   credits="${modcredits}" #optional
   authors="${modauthors}" #optional
   description='''${moddesc}'''
[[dependencies.${modid}]]
    modId="watermedia"
    mandatory=true
    versionRange="${watermediarange}"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.${modid}]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="${forgerange}" #mandatory
   ordering="NONE"
   side="BOTH"# Here's another dependency
[[dependencies.${modid}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraftversion}"
   ordering="NONE"
   side="BOTH"
