modLoader="javafml" #mandatory
loaderVersion="${fmlrange}"
license="${license}"
issueTrackerURL="https://github.com/${github}/issues" #optional

[[mods]] #mandatory
   modId="${modid}" #mandatory
   version="${modversion}" #mandatory
   displayName="${modname}" #mandatory
   displayTest="MATCH_VERSION"
   logoFile="pack.png" #optional
   credits="${modcredits}" #optional
   authors="${modauthors}" #optional
   description='''${moddesc}'''

[[dependencies.${modid}]]
    modId="watermedia"
    mandatory=true
    versionRange="${watermediarange}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="voicechat_api"
    mandatory=false
    versionRange="[${voicechat_api_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="forge"
    mandatory=true
    versionRange="${forgerange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftversion}"
    ordering="NONE"
    side="BOTH"
